### ISSUE TITLE
Id and Title missing from reserved keywords

### ISSUE THREAD

**Issue by wardweistra** [standardhealth/vscode-language-fsh#1]
https://github.com/standardhealth/vscode-language-fsh/blob/8dbbeb7a19b79808fde1d804ca41fe51398b9f29/syntaxes/fsh.tmLanguage.json#L23

In my Visual Studio Code these two are not recognized as reserved keywords, while in the show examples in the call they were :)

**Comment by kjmahalingam** [comment]
Hello. We apologize for not seeing this issue earlier. We have addressed this in the latest commits to this repository, and it is published in v1.0.1 in the Extension Marketplace.

**Comment by wardweistra** [comment]
Works perfectly now, thanks
